### ISSUE TITLE
Multiple targets for bitbake

### ISSUE THREAD

**Issue by pietrushnic** [3mdeb/yocto-docker#26]
Is it possible to add multiple targets for bitbake? Eg.

```
./yocto-docker/docker-bake.sh xen xen-image-minial xen-guest-image-minimal
```

**Comment by macpijan** [comment]
@pietrushnic It should be possible to do whatever bitbake allows to do. We should only proxy the command line parameters to the bitbake inside the container. 
I think in your case bitbake command:

```
bitbake xen && bitbake xen-image-minimal && bitbake xen-guest-image-minimal
```

would translate to:

```
/yocto-docker/docker-bake.sh xen && /yocto-docker/docker-bake.sh xen-image-minimal && /yocto-docker/docker-bake.sh xen-guest-image-minimal
```

**Comment by macpijan** [comment]
@pietrushnic IIUC you want to build multiple components with one line (for example `xen` and `xen-image-minimal`. I am pretty sure that it *should* be possible to just pass one after another in the command line to build both of them - and the same should apply to our script. The typical use-case is rather to build a single image, so I do not really use this feature. I can confirm if it works this way.

**Comment by macpijan** [comment]
@pietrushnic IIUC you want to build multiple components with one line (for example `xen` and `xen-image-minimal`. I am pretty sure that it *should* be possible to just pass one after another in the command line to build both of them - and the same should apply to our script. The typical use-case is rather to build a single image, so I do not really use this feature. I can confirm if it works this way.

**Comment by macpijan** [comment]
It is possible to build multiple packages by passing one after another, just as in the bitbake
